### ISSUE TITLE
0.2.7 config, use dataId and json

### ISSUE THREAD

**Issue by bytestory** [nacos-group/nacos-spring-boot-project#133]
dataId=app.config.iptables

content type=JSON
{
    "blacklist": "黑名单",
    "whitelist": "白名单"
}

@NacosValue(value = "${blacklist}", autoRefreshed = true)

dataId仅支持app_config_iptables，下划线方式命名

throws
java.lang.UnsupportedOperationException: Parsing is not yet supported for this type profile : iptables
	at com.alibaba.nacos.spring.util.ConfigParseUtils.toProperties(ConfigParseUtils.java:100)
	at com.alibaba.nacos.spring.util.ConfigParseUtils.toProperties(ConfigParseUtils.java:127)
	at com.alibaba.nacos.spring.util.NacosUtils.toProperties(NacosUtils.java:444)
	at com.alibaba.nacos.spring.core.env.NacosPropertySource.<init>(NacosPropertySource.java:67)
	at 
com.alibaba.nacos.spring.context.annotation.config.NacosConfigBeanDefinitionRegistrar.registerBeanDefinitions(NacosConfigBeanDefinitionRegistrar.java:73)

**Comment by meteorice** [comment]
这个和我的错一样使用注解@NacosPropertySource引入的配置类型会被错误覆盖
