### ISSUE TITLE
启动时 异常 java.lang.NullPointerException: null com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.replayDeferredEvents(DeferredApplicationEventPublisher.java:75) ~[nacos-spring-context-0.2.2-RC1.jar:na]

### ISSUE THREAD

**Issue by kitsrc** [nacos-group/nacos-spring-boot-project#19]
java.lang.NullPointerException: null
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[na:1.8.0_202]
	at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.replayDeferredEvents(DeferredApplicationEventPublisher.java:75) ~[nacos-spring-context-0.2.2-RC1.jar:na]
	at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.onApplicationEvent(DeferredApplicationEventPublisher.java:69) ~[nacos-spring-context-0.2.2-RC1.jar:na]
	at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.onApplicationEvent(DeferredApplicationEventPublisher.java:37) ~[nacos-spring-context-0.2.2-RC1.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at com.vandream.erp.som.SomServiceApplication.main(SomServiceApplication.java:93) [classes/:na]

**Comment by fangjian0423** [comment]
I think this is a compatibility issue about spring-boot, we will fix it soon.

**Comment by chuntaojun** [comment]
already fix in nacos-spring-project
