### ISSUE TITLE
Spring boot 2.1.1 启动时异常

### ISSUE THREAD

**Issue by kitsrc** [nacos-group/nacos-spring-boot-project#20]
nacos-client 1.0.0
项目启动时 打印如下异常 但应用启动成功 
异常日志如下：
o.s.c.a.nacos.NacosConfigProperties      : create config service error!properties=NacosConfigProperties{serverAddr='null', encode='null', group='DEFAULT_GROUP', prefix='null', fileExtension='properties', timeout=3000, endpoint='null', namespace='null', accessKey='null', secretKey='null', contextPath='null', clusterName='null', name='null', sharedDataids='null', refreshableDataids='null', extConfig=null},e=,

com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45) ~[nacos-api-1.0.0.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:41) ~[nacos-api-1.0.0.jar:na]
	at org.springframework.cloud.alibaba.nacos.NacosConfigProperties.configServiceInstance(NacosConfigProperties.java:343) ~[spring-cloud-alibaba-nacos-config-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:63) [spring-cloud-alibaba-nacos-config-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:97) [spring-cloud-context-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]

**Comment by fangjian0423** [comment]
Could you please provide your configuration properties like `application.properties`(`bootstrap.properties`) and the version of spring-boot.

**Comment by Logicf** [comment]
![image](https://user-images.githubusercontent.com/23493090/56801248-91d6f680-684f-11e9-90f4-ac5caf11d199.png)

**Comment by Logicf** [comment]
nacos-client 1.0.0 spring boot 2.1.1.release

**Comment by chuntaojun** [comment]
> nacos-client 1.0.0 spring boot 2.1.1.release

You use alibaba-cloud-naocs ？

**Comment by Hugo-X** [comment]
Seems you are using nacos with Spring Cloud,  you should follow this guide.
[https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html](https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html)

And be careful,  _spring.cloud.nacos.config.server-addr_  must be set in **bootstrap.properties**
