### ISSUE TITLE
升级到0.2.8 启动报错

### ISSUE THREAD

**Issue by gang0713** [nacos-group/nacos-spring-boot-project#200]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'discoveryAutoRegister': Injection of @NacosInjected dependencies is failed; nested exception is java.lang.ClassCastException: com.sun.proxy.$Proxy48 cannot be cast to java.util.Map
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:149) ~[spring-context-support-1.0.10.jar:?]

Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy48 cannot be cast to java.util.Map
	at com.alibaba.nacos.spring.beans.factory.annotation.AnnotationNacosInjectedBeanPostProcessor.getNacosProperties(AnnotationNacosInjectedBeanPostProcessor.java:145) ~[nacos-spring-context-1.1.0.jar:?]

**Comment by AdiHuang** [comment]
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.10</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.spring</groupId>
                    <artifactId>spring-context-support</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.spring</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>1.0.11</version>
        </dependency>
升级一下 spring-context-support的版本
