### ISSUE TITLE
Spring boot 2.4.6 接入nacos 2.0.3版本报错

### ISSUE THREAD

**Issue by zhengwe** [nacos-group/nacos-spring-boot-project#247]
pom 依赖：
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.11-beta</version>
        </dependency>
		 <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-actuator</artifactId>
            <version>0.2.11-beta</version>

服务启动报错：
java.lang.IllegalArgumentException: 'value' must not be null
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.6.jar!/:5.3.6]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:123) ~[spring-core-5.3.6.jar!/:5.3.6]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.3.6.jar!/:5.3.6]
	at org.springframework.core.env.AbstractPropertyResolver.resolvePlaceholders(AbstractPropertyResolver.java:202) ~[spring-core-5.3.6.jar!/:5.3.6]
	at org.springframework.core.env.AbstractEnvironment.resolvePlaceholders(AbstractEnvironment.java:619) ~[spring-core-5.3.6.jar!/:5.3.6]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.reqGlobalNacosConfig(NacosConfigLoader.java:120) ~[nacos-config-spring-boot-autoconfigure-0.2.11-beta.jar!/:0.2.11-beta]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.loadConfig(NacosConfigLoader.java:69) ~[nacos-config-spring-boot-autoconfigure-0.2.11-beta.jar!/:0.2.11-beta]
	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationContextInitializer.initialize(NacosConfigApplicationContextInitializer.java:89) ~[nacos-config-spring-boot-autoconfigure-0.2.11-beta.jar!/:0.2.11-beta]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:639) ~[spring-boot-2.4.6.jar!/:2.4.6]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:402) ~[spring-boot-2.4.6.jar!/:2.4.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.4.6.jar!/:2.4.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.6.jar!/:2.4.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) ~[spring-boot-2.4.6.jar!/:2.4.6]
	at com.lianlian.contract.ApplicationStarter.main(ApplicationStarter.java:26) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:1.0.0-SNAPSHOT]

**Comment by hujun-w-2** [comment]
please paste the configuration file

**Comment by zhengwe** [comment]
hello this is my configuration file

`
nacos:
  config:
    bootstrap:
      enable: true
  server-addr: xxx:8848
  data-ids: demo
  group: DEFAULT_GROUP
  type: yaml
  remote-first: true
  auto-refresh: true
  max-retry: 10
  enable-remote-sync-config: true
  config-retry-time: 2000
  config-long-poll-timeout: 10000
`

**Comment by zhengwe** [comment]
@hujun-w-2

**Comment by hujun-w-2** [comment]
我试试

**Comment by hujun-w-2** [comment]
你的配置文件直接截图吧，这样都不知道你格式对不对

**Comment by zhengwe** [comment]
configuration file's indentation is two
<img width="231" alt="image" src="https://user-images.githubusercontent.com/38490510/175480544-0d3dd156-9fe5-4187-85d4-ef43c5e9a62b.png">

**Comment by hujun-w-2** [comment]
层级结构不对，自己核对一下





------------------ 原始邮件 ------------------
发件人: zhengwe ***@***.***&gt;
发送时间: 2022年6月24日 14:59
收件人: nacos-group/nacos-spring-boot-project ***@***.***&gt;
抄送: 胡俊 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [nacos-group/nacos-spring-boot-project] Spring boot 2.4.6 接入nacos 2.0.3版本报错 (Issue #247)





 
configuration file's indentation is two

**Comment by zhengwe** [comment]
sorry 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/38490510/175493150-5ae35ffc-f46f-4944-a1a7-994237252d77.png">
