### ISSUE TITLE
使用nacos做配置中心，开启权限认证后报错：http error, code=403,msg=unknown user!

### ISSUE THREAD

**Issue by JeremyZheng** [nacos-group/nacos-spring-boot-project#276]
服务端版本，2.2.0
spring boot 版本：2.4.4
nacos-config-spring-boot-starter：0.2.12

配置文件：
```
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: xxxxxx
    group: xxx
    data-id: xxx
    type: yaml
    auto-refresh: true
    username: dev
    password: xxxx
```

错误信息：
com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg=unknown user!,
  at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:979)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:396)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:166)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:94)
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:63)
	at com.alibaba.nacos.spring.util.NacosUtils.getContent(NacosUtils.java:386)
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.reqNacosConfig(NacosConfigLoader.java:161)
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.reqGlobalNacosConfig(NacosConfigLoader.java:129)
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.loadConfig(NacosConfigLoader.java:69)
	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationContextInitializer.initialize(NacosConfigApplicationContextInitializer.java:89)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:637)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at com.sugon.dmsrks.api.DmsrksApiApplication.main(DmsrksApiApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

**Comment by JeremyZheng** [comment]
密码错误导致。。。
