### ISSUE TITLE
啥时候升级jdk17+ springboot3

### ISSUE THREAD

**Issue by luyanfeng** [nacos-group/nacos-spring-boot-project#285]
nacos-config-spring-boot-starter 和 nacos-discovery-spring-boot-starter
目前在集成springboot3时，出现兼容问题：
```java
java.lang.NoSuchMethodError: 'org.springframework.core.io.support.SpringFactoriesLoader org.springframework.core.io.support.SpringFactoriesLoader.forDefaultResourceLocation(java.lang.ClassLoader)'
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:459)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:455)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:272)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:252)
	at com.lyf.common.utils.SpringUtils.start(SpringUtils.java:55)
	at com.lyf.dubbo.DubboProviderApplication.main(DubboProviderApplication.java:32)
```
这是spring-core 5.xx 中没有 forDefaultResourceLocation这个方法，在spring-core6 中才有。

啥时候nacos的相关组件 升级jdk17+ springboot3

**Comment by guos** [comment]
same request

**Comment by hujun-w-2** [comment]
开源之夏项目已经在支持了，预计9月份可以发一个新版本
