### ISSUE TITLE
grpc相关问题

### ISSUE THREAD

**Issue by wjzxc123** [nacos-group/nacos-spring-boot-project#299]
```java
2023-07-28T16:45:59.384+08:00  INFO 29476 --- [           main] com.alibaba.nacos.common.remote.client   : [68983657-9d08-48eb-8c7a-c87ab8998996_config-0] Try to connect to server on start up, server: {serverIp = '192.168.119.128', server main port = 8999}
2023-07-28T16:45:59.386+08:00 DEBUG 29476 --- [-172.16.100.102] sun.rmi.transport.tcp                    : RMI TCP Connection(1)-172.16.100.102: (port 60504) op = 80
2023-07-28T16:45:59.386+08:00 DEBUG 29476 --- [-172.16.100.102] javax.management.remote.rmi              : [javax.management.remote.rmi.RMIConnectionImpl@3eedf8e0: connectionId=rmi://172.16.100.102  1] closing.
2023-07-28T16:45:59.386+08:00 DEBUG 29476 --- [-172.16.100.102] javax.management.remote.rmi              : [javax.management.remote.rmi.RMIConnectionImpl@3eedf8e0: connectionId=rmi://172.16.100.102  1] closed.
2023-07-28T16:45:59.399+08:00  INFO 29476 --- [           main] c.a.n.c.remote.client.grpc.GrpcClient    : grpc client connection server:192.168.119.128 ip,serverPort:9999,grpcTslConfig:{"sslProvider":"","enableTls":false,"mutualAuthEnable":false,"trustAll":false}
2023-07-28T16:45:59.401+08:00 DEBUG 29476 --- [           main] c.a.n.s.io.grpc.ManagedChannelRegistry   : Unable to find OkHttpChannelProvider

java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.okhttp.OkHttpChannelProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:375) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:139) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:103) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.buildChannel(GrpcClient.java:373) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:184) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:325) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:363) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:891) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1038) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:946) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:403) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:184) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:96) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:63) ~[nacos-spring-context-1.1.1.jar:na]
	at com.alibaba.nacos.spring.util.NacosUtils.getContent(NacosUtils.java:386) ~[nacos-spring-context-1.1.1.jar:na]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.reqNacosConfig(NacosConfigLoader.java:161) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.reqGlobalNacosConfig(NacosConfigLoader.java:129) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.loadConfig(NacosConfigLoader.java:69) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationContextInitializer.initialize(NacosConfigApplicationContextInitializer.java:89) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:606) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:386) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[spring-boot-3.1.0.jar:3.1.0]
	at com.licon.YyAuthApplication.main(YyAuthApplication.java:11) ~[classes/:na]

2023-07-28T16:45:59.401+08:00 DEBUG 29476 --- [           main] c.a.n.s.io.grpc.ManagedChannelRegistry   : Unable to find NettyChannelProvider

java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.netty.NettyChannelProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:375) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:144) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:103) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.buildChannel(GrpcClient.java:373) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:184) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:325) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:363) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:891) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1038) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:946) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:403) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:184) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:96) ~[nacos-client-2.2.3.jar:na]
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:63) ~[nacos-spring-context-1.1.1.jar:na]
	at com.alibaba.nacos.spring.util.NacosUtils.getContent(NacosUtils.java:386) ~[nacos-spring-context-1.1.1.jar:na]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.reqNacosConfig(NacosConfigLoader.java:161) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.reqGlobalNacosConfig(NacosConfigLoader.java:129) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.loadConfig(NacosConfigLoader.java:69) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationContextInitializer.initialize(NacosConfigApplicationContextInitializer.java:89) ~[nacos-config-spring-boot-autoconfigure-0.2.12.jar:0.2.12]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:606) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:386) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[spring-boot-3.1.0.jar:3.1.0]
	at com.licon.YyAuthApplication.main(YyAuthApplication.java:11) ~[classes/:na]

``` 

麻烦问一下，这是什么原因

**Comment by wjzxc123** [comment]
配置如下：
```yaml
nacos:
  config:
    server-addr: 192.168.119.128:8999
    username: root
    password: root
    namespace: yy-cloud
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
    data-id: yy-config-common
```
