### ISSUE TITLE
grpc相关问题com.alibaba.nacos.shaded.io.grpc.okhttp.OkHttpChannelProvider

### ISSUE THREAD

**Issue by 2777192213** [nacos-group/nacos-spring-boot-project#334]
2024-07-10 14:26:29.423  INFO 30332 --- [           main] [                                ] c.a.n.c.remote.client.grpc.GrpcClient    : grpc client connection server:localhost ip,serverPort:9848,grpcTslConfig:{"sslProvider":"","enableTls":false,"mutualAuthEnable":false,"trustAll":false}
2024-07-10 14:26:29.425 DEBUG 30332 --- [           main] [                                ] c.a.n.s.io.grpc.ManagedChannelRegistry   : Unable to find OkHttpChannelProvider

java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.okhttp.OkHttpChannelProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:375) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:137) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:103) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.buildChannel(GrpcClient.java:565) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:212) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:364) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:349) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:1100) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1248) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:1146) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:472) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:188) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:99) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:89) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:141) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:50) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:46) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.doInitialize(PropertySourceBootstrapConfiguration.java:120) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:110) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:400) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
	at com.aspire.lucky.StartApplication.main(StartApplication.java:15) ~[classes/:na]

2024-07-10 14:26:29.429 DEBUG 30332 --- [           main] [                                ] c.a.n.s.io.grpc.ManagedChannelRegistry   : Unable to find NettyChannelProvider

java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.netty.NettyChannelProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:375) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:142) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:103) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.buildChannel(GrpcClient.java:565) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:212) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:364) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:349) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:1100) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1248) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:1146) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:472) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:188) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:99) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:89) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:141) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:50) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:46) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.doInitialize(PropertySourceBootstrapConfiguration.java:120) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:110) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:400) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
	at com.aspire.lucky.StartApplication.main(StartApplication.java:15) ~[classes/:na]

2024-07-10 14:26:29.431 DEBUG 30332 --- [           main] [                                ] c.a.n.s.io.grpc.ManagedChannelRegistry   : Unable to find UdsNettyChannelProvider

java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.netty.UdsNettyChannelProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:375) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:147) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:103) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.buildChannel(GrpcClient.java:565) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:212) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:364) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:349) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:1100) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1248) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:1146) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:472) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:188) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:99) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:89) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:141) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) ~[spring-cloud-starter-alibaba-nacos-config-2023.0.1.0.jar:2023.0.1.0]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:50) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:46) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.doInitialize(PropertySourceBootstrapConfiguration.java:120) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:110) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:400) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
	at com.aspire.lucky.StartApplication.main(StartApplication.java:15) ~[classes/:na]

Can someone help me with this

**Comment by hujun-w-2** [comment]
nacos-spring-boot-project 的版本是多少

**Comment by 2777192213** [comment]
> nacos-spring-boot-project 的版本是多少

nacos-client 2.3.2

**Comment by 2777192213** [comment]
> > nacos-spring-boot-project 的版本是多少
> 
> nacos-client 2.3.2



> nacos-spring-boot-project 的版本是多少

使用的是spring-cloud 2023.0.1内置的

**Comment by 2777192213** [comment]
因为我是nacos安装的windows系统上的，猜测可能是因为系统因素导致的

**Comment by FU-SHENG-Z** [comment]
你解决了吗 我也遇到这个问题了 一直搞不明白哪里的问题

**Comment by 2777192213** [comment]
> 你解决了吗 我也遇到这个问题了 一直搞不明白哪里的问题

还没有解决

**Comment by FU-SHENG-Z** [comment]
> > 你解决了吗 我也遇到这个问题了 一直搞不明白哪里的问题
> 
> 还没有解决
难受

**Comment by FU-SHENG-Z** [comment]
> > 你解决了吗 我也遇到这个问题了 一直搞不明白哪里的问题
> 
> 还没有解决

但是我刚才又弄了一下 就是这个应该也不影响正常使用 应该是阿里不知道哪里出的BUG
