### ISSUE TITLE
Springboot2 启动报错Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.api.config.ConfigType

### ISSUE THREAD

**Issue by chenglin321** [nacos-group/nacos-spring-boot-project#40]
错误信息：
java.lang.NoClassDefFoundError: com/alibaba/nacos/api/config/ConfigType
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_211]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_211]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_211]
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:112) ~[na:1.8.0_211]
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:109) ~[na:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_211]
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:109) ~[na:1.8.0_211]
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85) ~[na:1.8.0_211]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266) ~[na:1.8.0_211]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[na:1.8.0_211]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_211]
	at java.lang.Class.createAnnotationData(Class.java:3521) ~[na:1.8.0_211]
	at java.lang.Class.annotationData(Class.java:3510) ~[na:1.8.0_211]
	at java.lang.Class.getAnnotations(Class.java:3446) ~[na:1.8.0_211]
	at org.springframework.core.type.StandardAnnotationMetadata.<init>(StandardAnnotationMetadata.java:70) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.annotation.AnnotatedGenericBeanDefinition.<init>(AnnotatedGenericBeanDefinition.java:58) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:216) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:145) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:135) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:158) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:135) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.load(SpringApplication.java:717) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at com.cnhis.cloudhealth.crm.CrmApplication.main(CrmApplication.java:31) [classes/:na]
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.api.config.ConfigType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_211]
	... 27 common frames omitted

Process finished with exit code 1

依赖包：

[INFO] +- com.alibaba.boot:nacos-config-spring-boot-starter:jar:0.2.2:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.1.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.1.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.1:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.1:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:compile
[INFO] |  +- com.alibaba.nacos:nacos-spring-context:jar:0.3.1:compile
[INFO] |  |  +- com.alibaba.nacos:nacos-client:jar:0.6.2:compile
[INFO] |  |  |  +- com.alibaba.nacos:nacos-common:jar:0.6.2:compile
[INFO] |  |  |  +- com.alibaba.nacos:nacos-api:jar:0.6.2:compile
[INFO] |  |  |  \- org.codehaus.jackson:jackson-mapper-lgpl:jar:1.9.6:compile
[INFO] |  |  |     \- org.codehaus.jackson:jackson-core-lgpl:jar:1.9.6:compile
[INFO] |  |  \- com.alibaba.spring:spring-context-support:jar:1.0.2:compile
[INFO] |  +- com.alibaba.boot:nacos-config-spring-boot-autoconfigure:jar:0.2.2:compile
[INFO] |  \- com.alibaba.boot:nacos-spring-boot-base:jar:0.2.2:compile

**Comment by chuntaojun** [comment]
your nacos-client/api/common version so old, ensure these version is 1.1.0+
