### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/RateLimiterring

### ISSUE THREAD

**Issue by zhanglizhouchanghe** [nacos-group/nacos-spring-boot-project#63]
spirng boot 版本1.4.1.RELEASE，nacos-config-spring-boot-starter版本0.1.3
2019-09-02 15:41:17.533  INFO 20248 --- [           main] c.a.b.n.c.u.NacosConfigPropertiesUtils   : nacosConfigProperties : com.alibaba.boot.nacos.config.properties.NacosConfigProperties@3e10dc6
2019-09-02 15:41:17.690  WARN 20248 --- [           main] o.s.boot.SpringApplication               : Error handling failed (ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.context.annotation.AnnotationConfigApplicationContext@5f6722d3: startup date [Thu Jan 01 08:00:00 CST 1970]; root of context hierarchy)
2019-09-02 15:41:17.703 ERROR 20248 --- [           main] o.s.boot.SpringApplication               : Application startup failed

com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/RateLimiter
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2232) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764) ~[guava-11.0.2.jar:na]
	at com.alibaba.nacos.client.config.impl.Limiter.isLimit(Limiter.java:62) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.impl.HttpSimpleClient.httpGet(HttpSimpleClient.java:47) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:80) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:48) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:234) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:173) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:122) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:58) ~[nacos-spring-context-0.3.3.jar:na]
	at com.alibaba.nacos.spring.util.NacosUtils.getContent(NacosUtils.java:312) ~[nacos-spring-context-0.3.3.jar:na]
	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.reqNacosConfig(NacosConfigUtils.java:115) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.reqGlobalNacosConfig(NacosConfigUtils.java:96) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.loadConfig(NacosConfigUtils.java:66) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationInitializer.initialize(NacosConfigApplicationInitializer.java:75) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:349) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:138) [spring-cloud-context-1.1.7.RELEASE.jar:1.1.7.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84) [spring-cloud-context-1.1.7.RELEASE.jar:1.1.7.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62) [spring-cloud-context-1.1.7.RELEASE.jar:1.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121) [spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at cn.sino.DiscsApplication.main(DiscsApplication.java:14) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/RateLimiter
	at com.alibaba.nacos.client.config.impl.Limiter$1.call(Limiter.java:65) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.impl.Limiter$1.call(Limiter.java:62) ~[nacos-client-1.1.3.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228) ~[guava-11.0.2.jar:na]
	... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.RateLimiter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 39 common frames omitted

2019-09-02 15:41:17.705  WARN 20248 --- [           main] o.s.boot.SpringApplication               : Error handling failed (no error message)
2019-09-02 15:41:17.706 ERROR 20248 --- [           main] o.s.boot.SpringApplication               : Application startup failed

com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/RateLimiter
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2232) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764) ~[guava-11.0.2.jar:na]
	at com.alibaba.nacos.client.config.impl.Limiter.isLimit(Limiter.java:62) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.impl.HttpSimpleClient.httpGet(HttpSimpleClient.java:47) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:80) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:48) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:234) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:173) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:122) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:58) ~[nacos-spring-context-0.3.3.jar:na]
	at com.alibaba.nacos.spring.util.NacosUtils.getContent(NacosUtils.java:312) ~[nacos-spring-context-0.3.3.jar:na]
	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.reqNacosConfig(NacosConfigUtils.java:115) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.reqGlobalNacosConfig(NacosConfigUtils.java:96) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.loadConfig(NacosConfigUtils.java:66) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationInitializer.initialize(NacosConfigApplicationInitializer.java:75) ~[nacos-config-spring-boot-autoconfigure-0.1.3.jar:0.1.3]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:349) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:138) ~[spring-cloud-context-1.1.7.RELEASE.jar:1.1.7.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84) ~[spring-cloud-context-1.1.7.RELEASE.jar:1.1.7.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62) ~[spring-cloud-context-1.1.7.RELEASE.jar:1.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at cn.sino.DiscsApplication.main(DiscsApplication.java:14) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/RateLimiter
	at com.alibaba.nacos.client.config.impl.Limiter$1.call(Limiter.java:65) ~[nacos-client-1.1.3.jar:na]
	at com.alibaba.nacos.client.config.impl.Limiter$1.call(Limiter.java:62) ~[nacos-client-1.1.3.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313) ~[guava-11.0.2.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228) ~[guava-11.0.2.jar:na]
	... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.RateLimiter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 39 common frames omitted

**Comment by chuntaojun** [comment]
You may have a look you the existence of the guava version of this Class, if not, should be the problem of version rely on

**Comment by zhanglizhouchanghe** [comment]
> You may have a look you the existence of the guava version of this Class, if not, should be the problem of version rely on

一开始引入是存在这个guava的版本冲突的，但是我在nacos-config的maven中把它给排除掉了，我都maven依赖树只保留一个guava，但是依旧不行。

**Comment by zhanglizhouchanghe** [comment]
> 
> 
> You may have a look you the existence of the guava version of this Class, if not, should be the problem of version rely on

找到原因了，其他maven引用的guava版本太低，导致没有com/google/common/util/concurrent/RateLimiter 。再次请教下nacos的docker部署，单节点下怎么配置账号密码，nacos/nacos这个默认密码太不安全了
