### ISSUE TITLE
spring boot 0.2.2 版本中开户预加载后 java -jar xxx.jar --spring.profiles.active=test启动有bug

### ISSUE THREAD

**Issue by wuming-hero** [nacos-group/nacos-spring-boot-project#97]
spring boot 0.2.2 版本中开户预加载，使用java -jar 指定环境启动时，发现加载的数据有问题。
data-id，groupId 等数据切换为测试环境的（即application-test.yml），但dubbo配置信息却是application.yml中的

**Comment by chuntaojun** [comment]
使用 0.2.3看下，这个问题记得在 0.2.3修复了

**Comment by wuming-hero** [comment]
0.2.3版本中的spring版本与我们项目中目前使用的不一致。目前项目中统一使用spring-boot-2.0.2,spring-5.0.6版本；
有没有使用交流群啊，可以一起交流下

**Comment by wuming-hero** [comment]
java.lang.UnsupportedOperationException: Parsing is not yet supported for this type profile : server
	at com.alibaba.nacos.spring.util.ConfigParseUtils.toProperties(ConfigParseUtils.java:91) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.util.ConfigParseUtils.toProperties(ConfigParseUtils.java:120) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.util.NacosUtils.toProperties(NacosUtils.java:414) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.core.env.NacosPropertySource.<init>(NacosPropertySource.java:66) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder.doBuild(AbstractNacosPropertySourceBuilder.java:173) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder.build(AbstractNacosPropertySourceBuilder.java:103) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.buildNacosPropertySources(NacosPropertySourcePostProcessor.java:144) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.processPropertySource(NacosPropertySourcePostProcessor.java:129) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.postProcessBeanFactory(NacosPropertySourcePostProcessor.java:115) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.util.NacosBeanUtils.invokeNacosPropertySourcePostProcessor(NacosBeanUtils.java:351) ~[nacos-spring-context-0.3.3.jar!/:na]
	at com.alibaba.nacos.spring.context.annotation.config.NacosConfigBeanDefinitionRegistrar.registerBeanDefinitions(NacosConfigBeanDefinitionRegistrar.java:67) ~[nacos-spring-context-0.3.3.jar!/:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:358) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_162]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:357) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:145) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:328) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
	at com.ixiye.sanya.account.Application.main(Application.java:22) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [account-server-1.0.0-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [account-server-1.0.0-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [account-server-1.0.0-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [account-server-1.0.0-SNAPSHOT.jar:na]

**Comment by wuming-hero** [comment]
定位到问题发生NacosUtils中的181行
```java
public static String readTypeFromDataId(String dataId) {
        if (StringUtils.isEmpty(dataId)) {
            return dataId;
        }
        int index = dataId.lastIndexOf(".");
        return index != -1 ? dataId.substring(index + 1) : "";
    }
```
从dataId从取type,我的dataId=com.ixiye.kt.server，然后获取的type的值为server,
后面还是在该工具类第409行，对type进行判断
```java
public static Properties toProperties(String dataId, String group, String text, String type) {
        type = type.toLowerCase();
        if ("yml".equalsIgnoreCase(type)) {
            type = "yaml";
        }
        return ConfigParseUtils.toProperties(dataId, group, text, type);
    }
```
于是就有了上面的错误信息
应该是个bug吧，或者在配置中需要额外的配置，请看到信息即时回复，谢谢

**Comment by wuming-hero** [comment]
上面问题已解决

dataId命名上，后面加上`.yml`
